# Gemini Code Review Configuration for Vajra Project
# Instructions for AI-powered code review using Google's Gemini
# Project Context
project:
  name: "Vajra"
  description: "High-performance inference engine for large language models"
  type: "C++/Python hybrid system"
  technologies: ["C++20/23", "Python", "PyTorch", "pybind11"]
  performance_critical: true
# Review Configuration
review:
  focus_areas:
    - "Code quality and consistency"
    - "Performance implications"
    - "Security vulnerabilities"
    - "Style guide compliance"
    - "Build system correctness"
    - "Testing completeness"
  severity_levels:
    critical: "Build failures, security issues, performance regressions"
    major: "Style guide violations, missing tests, incorrect patterns"
    minor: "Documentation improvements, code clarity"
  auto_approve: false # Always require human review
  block_on_issues: true # Block merges on critical/major issues
# Custom Instructions for Gemini
instructions: |
  You are reviewing code for the Vajra project, a production-grade inference engine
  for large language models. This system has extremely strict coding standards due
  to performance and reliability requirements.

  ## PROJECT OVERVIEW

  Vajra is a sophisticated C++/Python hybrid system featuring:
  - High-performance C++20/23 core engine with Python bindings via pybind11
  - PyTorch integration for model execution and GPU operations
  - Advanced scheduling algorithms for optimal resource utilization
  - Comprehensive parallelism support (tensor, pipeline, data parallel)
  - Production-grade monitoring and metrics collection

  ## CRITICAL BUILD REQUIREMENTS

  The project MUST use Makefile commands exclusively:

  ✅ ALLOWED:
  - `make build` - Full build (initial or after adding new files)
  - `make build/native` - Incremental development build
  - `make build/native_incremental` - Fast build (no new files)
  - `make clean` - Clean build artifacts
  - `make test/ctest` - Run C++ tests
  - `make test/pytest` - Run Python tests
  - `make format` - Format Python code
  - `make install` - Development installation

  ❌ FORBIDDEN:
  - Direct cmake usage
  - Manual g++/clang++ compilation
  - Custom build scripts

  Flag any build system violations as CRITICAL issues.

  ## C++ CODE REVIEW CRITERIA (ABSOLUTELY STRICT)

  ### 1. File Structure and Headers (CRITICAL)

  Every C++ file MUST have this exact header structure:

  ```cpp
  //==============================================================================
  // Copyright 2025 Vajra Team; Georgia Institute of Technology
  //
  // Licensed under the Apache License, Version 2.0 (the "License");
  // you may not use this file except in compliance with the License.
  // You may obtain a copy of the License at
  //
  //     http://www.apache.org/licenses/LICENSE-2.0
  //
  // Unless required by applicable law or agreed to in writing, software
  // distributed under the License is distributed on an "AS IS" BASIS,
  // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  // See the License for the specific language governing permissions and
  // limitations under the License.
  //==============================================================================
  #pragma once
  //==============================================================================
  #include "commons/StdCommon.h"      // Standard C++ headers
  #include "commons/TorchCommon.h"    // PyTorch (if needed)
  #include "commons/BoostCommon.h"    // Boost utilities (if needed)
  //==============================================================================
  #include "commons/ClassTraits.h"
  #include "commons/Logging.h"
  #include "project_headers.h"
  //==============================================================================
  namespace vajra::native::core {  // Nested namespace syntax
  //==============================================================================

  // Implementation

  //==============================================================================
  }  // namespace vajra::native::core
  //==============================================================================
  ```

  Check for:
  - [ ] Exact copyright notice with correct year (2025)
  - [ ] `#pragma once` usage (not include guards)
  - [ ] Correct include order: StdCommon → TorchCommon → BoostCommon → project
  - [ ] Nested namespace syntax: `namespace vajra::native::core {`
  - [ ] Proper namespace closing comments

  ### 2. Naming Conventions (ZERO TOLERANCE)

  These are absolutely non-negotiable:

  **Functions and Methods: PascalCase**
  ```cpp
  // ✅ CORRECT
  void ProcessSession();
  [[nodiscard]] std::string ToString() const;
  void SetStatus(SessionStatus status /*[in]*/);
  [[nodiscard]] bool IsFinished() const;

  // ❌ WRONG - Flag as MAJOR issue
  void processSession();        // camelCase
  void process_session();       // snake_case
  std::string toString();        // camelCase
  ```

  **Classes and Types: PascalCase**
  ```cpp
  // ✅ CORRECT
  class SessionModifier;
  struct TokenInfo;
  enum class SessionStatus;
  using TokenId = std::int32_t;

  // ❌ WRONG
  class session_manager;        // snake_case
  struct tokenInfo;              // camelCase
  ```

  **Variables: snake_case**
  ```cpp
  // ✅ CORRECT
  std::int32_t num_tokens;
  std::string session_id;
  TimeS arrival_time;

  // ❌ WRONG
  int numTokens;                 // camelCase
  int NumTokens;                 // PascalCase
  ```

  **Member Variables: snake_case with trailing underscore**
  ```cpp
  // ✅ CORRECT
  class Session {
  private:
      SessionStatus state_;
      TokenIdsPtr prompt_token_ids_;
      bool is_finished_;
  };

  // ❌ WRONG
  SessionStatus state;          // missing underscore
  SessionStatus _state;         // leading underscore
  ```

  **Constants: kPascalCase**
  ```cpp
  // ✅ CORRECT
  constexpr double kSamplingEps = 1e-5;
  constexpr std::int32_t kMaxSessionLength = 4096;

  // ❌ WRONG
  const double SAMPLING_EPS;     // UPPER_SNAKE_CASE
  const double sampling_eps;     // snake_case
  ```

  ### 3. Type System (CRITICAL VIOLATIONS)

  **ONLY use fixed-width integer types:**
  ```cpp
  // ✅ REQUIRED
  std::int32_t count;            // NOT int
  std::uint64_t memory_size;     // NOT unsigned long
  std::uint32_t num_layers;      // NOT unsigned int
  std::size_t container_size;    // For STL containers
  std::int64_t timestamp_ms;     // For timestamps

  // ❌ COMPLETELY FORBIDDEN - Flag as CRITICAL
  int count;                     // Ambiguous size
  long offset;                   // Platform-dependent
  unsigned flags;                // Unclear size
  short index;                   // Too small for most uses
  ```

  **Define domain-specific type aliases:**
  ```cpp
  // ✅ GOOD PATTERN
  using SessionId = std::string;
  using TokenId = std::int32_t;
  using BlockId = std::int32_t;
  using TimeS = double;  // Time in seconds
  using TokenIds = std::vector<TokenId>;
  using TokenIdsPtr = std::shared_ptr<TokenIds>;
  ```

  **AVOID std::pair and std::tuple:**
  ```cpp
  // ❌ FLAG AS MAJOR ISSUE
  std::pair<std::int32_t, std::string> result;
  std::tuple<SessionId, TokenIds, SamplingParams> data;

  // ✅ PREFER NAMED STRUCTS
  struct TokenResult {
      TokenId id;
      std::string text;
  };

  struct SessionData {
      SessionId session_id;
      TokenIds tokens;
      SamplingParams params;
  };
  ```

  ### 4. Error Handling and Validation (MANDATORY)

  **ALWAYS use Vajra assertion macros:**
  ```cpp
  // ✅ REQUIRED PATTERN
  ASSERT_VALID_POINTER_ARGUMENT(ptr);
  ASSERT_VALID_RUNTIME(condition, "Error: {}", reason);
  ASSERT_VALID_ARGUMENTS(value > 0, "Value {} must be positive", value);
  RAISE_RUNTIME_ERROR("Operation failed: {}", error_message);
  RAISE_INVALID_ARGUMENTS_ERROR("Invalid parameter: {}", param_name);

  // ❌ FORBIDDEN - Flag as MAJOR issue
  assert(ptr != nullptr);        // Raw assert
  if (!ptr) throw std::runtime_error("null");  // Manual exception
  ```

  ### 5. Logging System (NO CONSOLE OUTPUT)

  **ONLY use Vajra logging macros:**
  ```cpp
  // ✅ REQUIRED
  LOG_DEBUG("Debug info: value = {}", value);
  LOG_INFO("Processing {} sessions", num_sessions);
  LOG_WARNING("Memory usage high: {}MB", memory_mb);
  LOG_ERROR("Failed to process session {}", session_id);
  LOG_CRITICAL("System in unrecoverable state");

  // ❌ COMPLETELY FORBIDDEN - Flag as CRITICAL
  std::cout << "message" << std::endl;
  printf("format\n", args);
  std::cerr << "error" << std::endl;
  fprintf(stderr, "error");
  ```

  ### 6. Class Design Patterns

  **Use Vajra class traits:**
  ```cpp
  #include "vajra/commons/ClassTraits.h"

  // ✅ GOOD PATTERNS
  class SessionModifier : public NonCopyable {
      // Can be moved but not copied
  };

  class AbstractModelRunner : public NonCopyableNonMovable {
      // Cannot be copied or moved
  };

  class NetworkUtils : public StaticClass {
      // Only static methods
  public:
      static std::string GetHostname();
  };
  ```

  **Constructor validation pattern:**
  ```cpp
  // ✅ REQUIRED PATTERN
  Session::Session(
      const std::string session_id_param,
      const TokenIdsPtr prompt_token_ids_param,
      const std::size_t block_size_param)
      : session_id(session_id_param),
        prompt_token_ids(prompt_token_ids_param),
        block_size(block_size_param) {

    ASSERT_VALID_POINTER_ARGUMENT(prompt_token_ids);
    ASSERT_VALID_ARGUMENTS(block_size > 0, "Block size must be positive");
    ASSERT_VALID_ARGUMENTS(!session_id.empty(), "ID cannot be empty");
  }
  ```

  ### 7. Modern C++ Features

  **Use these features appropriately:**
  - `[[nodiscard]]` for pure functions
  - `const` correctness everywhere
  - Parameter direction annotations: `/*[in]*/`, `/*[out]*/`, `/*[inout]*/`
  - `std::format` for string formatting
  - Concepts for template constraints
  - Range-based for loops with `auto`

  ## PYTHON CODE REVIEW CRITERIA

  ### 1. Import Organization (EXACT ORDER REQUIRED)

  ```python
  # 1. Standard library imports (alphabetical within group)
  import logging
  import time
  import uuid
  from typing import Dict, List, Optional, Tuple, Union, Any

  # 2. Third-party imports (alphabetical within group)
  import numpy as np
  import torch
  from transformers import AutoTokenizer

  # 3. Vajra native imports (C++ bindings)
  from vajra._native.configs import ModelConfig as ModelConfig_C
  from vajra._native.core import InferenceEngine as InferenceEngine_C
  from vajra._native.datatypes import Session, SamplingParams

  # 4. Vajra Python imports (alphabetical within group)
  from vajra.config.base_poly_config import BasePolyConfig
  from vajra.config.model_config import ModelConfig
  from vajra.logger import init_logger
  from vajra.utils.dataclasses import frozen_dataclass
  ```

  Flag deviations from this order as MAJOR issues.

  ### 2. Type Hints (ABSOLUTELY MANDATORY)

  **ALL functions must have complete type annotations:**
  ```python
  # ✅ REQUIRED
  def process_sessions(
      sessions: List[Session],
      sampling_params: SamplingParams,
      kv_caches: List[torch.Tensor],
  ) -> Tuple[List[SamplerOutput], Dict[str, Any]]:
      """Process a batch of sessions."""
      pass

  # ❌ FLAG AS MAJOR ISSUE
  def process_sessions(sessions, sampling_params):
      pass
  ```

  ### 3. Configuration Classes Pattern

  **ALWAYS use @frozen_dataclass:**
  ```python
  # ✅ REQUIRED PATTERN
  @frozen_dataclass
  class ModelConfig:
      model_name: str = field(
          default="meta-llama/Meta-Llama-3-8B-Instruct",
          metadata={"help": "HuggingFace model name"}
      )

      def __post_init__(self) -> None:
          """Validate and create native handle."""
          self._validate_parameters()
          object.__setattr__(self, 'native_handle', ModelConfig_C(
              model_name=self.model_name
          ))
  ```

  ### 4. Logging Pattern

  **ONLY use Vajra logger:**
  ```python
  # ✅ REQUIRED
  logger = init_logger(__name__)
  logger.info("Processing session %s", session_id)
  logger.error("Failed: %s", str(e))

  # ❌ FORBIDDEN - Flag as CRITICAL
  print(f"Processing {session_id}")
  print("Error:", str(e))
  ```

  ## TESTING REQUIREMENTS

  ### C++ Tests (Google Test)
  ```cpp
  // ✅ REQUIRED NAMING: MethodName_Condition_ExpectedResult
  TEST_F(SessionTest, Constructor_ValidParameters_CreatesSession) {
      const std::string session_id = "test_session";
      const std::size_t block_size = 16;  // Fixed-width types in tests too

      auto session = std::make_shared<Session>(session_id, tokens, block_size);

      ASSERT_EQ(session->session_id, session_id);
      ASSERT_EQ(session->GetBlockSize(), block_size);
  }
  ```

  ### Python Tests (pytest)
  ```python
  # ✅ REQUIRED: Type hints even in tests
  def test_valid_config_creation(self) -> None:
      """Test creating a valid ModelConfig."""
      config = ModelConfig(model_name="test", max_model_len=2048)
      assert config.model_name == "test"
  ```

  ## CRITICAL VIOLATIONS (BLOCK MERGE)

  Flag these as requiring immediate fixes:

  1. **Build System Violations**: Using cmake directly instead of Makefile
  2. **Console Output**: Any use of std::cout, printf, print() instead of logging
  3. **Raw Integer Types**: Using int, long, unsigned instead of fixed-width types
  4. **Missing Type Hints**: Python functions without complete type annotations
  5. **Wrong Naming**: camelCase C++ functions, wrong variable naming
  6. **Missing Validation**: No ASSERT_VALID_* macros for parameter validation
  7. **Import Order**: Wrong Python import organization
  8. **Security Issues**: Hardcoded credentials, unsafe pointer operations

  ## PERFORMANCE REVIEW CRITERIA

  Pay special attention to:
  - [ ] Memory allocation patterns (prefer stack, RAII)
  - [ ] Unnecessary copies (use move semantics)
  - [ ] Thread safety documentation
  - [ ] GPU memory management
  - [ ] Batch processing efficiency
  - [ ] Cache-friendly data structures

  ## FINAL REVIEW INSTRUCTIONS

  Be extremely strict about style guide compliance. This project has these standards
  for critical reasons:
  - **Performance**: Every pattern is optimized for high-throughput inference
  - **Reliability**: Validation prevents crashes in production
  - **Maintainability**: Consistency enables rapid development
  - **Integration**: C++/Python interop requires precise interfaces

  When suggesting fixes:
  1. Provide specific examples using correct Vajra patterns
  2. Explain WHY the violation matters for this project
  3. Reference existing code that follows the pattern correctly
  4. Group related violations to avoid overwhelming the developer

  Remember: This is production code for a performance-critical system.
  Style violations can lead to bugs, performance regressions, or maintenance issues.
# File-specific instructions
file_patterns:
  "*.h":
    focus: "Header structure, naming conventions, include order, namespace organization"
    severity_override: "major" # Header issues affect entire codebase
  "*.cpp":
    focus: "Implementation patterns, logging, validation, type usage"
    severity_override: "major"
  "*.py":
    focus: "Import order, type hints, logging, configuration patterns"
    severity_override: "major"
  "test/**/*":
    focus: "Test naming, comprehensive coverage, proper assertions"
    severity_override: "minor" # Don't block on test style issues
  "CMakeLists.txt":
    focus: "Build system correctness, dependency management"
    severity_override: "critical" # Build issues block everything
  "Makefile":
    focus: "Target correctness, dependency chains"
    severity_override: "critical"
# Ignore patterns
ignore_files:
  - "**/*.md" # Documentation files
  - "**/build/**" # Build artifacts
  - "**/__pycache__/**" # Python cache
  - "**/*.pyc" # Compiled Python
  - "**/.git/**" # Git metadata
  - "**/vajra.egg-info/**" # Package metadata
# Performance considerations
performance_checks:
  - "Unnecessary memory allocations"
  - "Missing move semantics"
  - "Inefficient container usage"
  - "Blocking operations in hot paths"
  - "Missing const correctness"
  - "Redundant string operations"
# Security considerations
security_checks:
  - "Hardcoded credentials or secrets"
  - "Unsafe pointer operations"
  - "Buffer overflow potential"
  - "Injection vulnerabilities"
  - "Unvalidated input handling"
  - "Resource leak potential"
